//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SellYourTime.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить фото.
        /// </summary>
        public static string Addphoto {
            get {
                return ResourceManager.GetString("Addphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Админ-Страница.
        /// </summary>
        public static string AdmPage {
            get {
                return ResourceManager.GetString("AdmPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Админ-панель.
        /// </summary>
        public static string AdmPanel {
            get {
                return ResourceManager.GetString("AdmPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все предложения.
        /// </summary>
        public static string AllOffers {
            get {
                return ResourceManager.GetString("AllOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все пользователи.
        /// </summary>
        public static string AllUsers {
            get {
                return ResourceManager.GetString("AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купить.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покупатель (Дата покупки).
        /// </summary>
        public static string Buyer {
            get {
                return ResourceManager.GetString("Buyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покупки у Профиля.
        /// </summary>
        public static string BuyingFrom {
            get {
                return ResourceManager.GetString("BuyingFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        public static string ChangePass {
            get {
                return ResourceManager.GetString("ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма изменения пароля.
        /// </summary>
        public static string ChangePassForm {
            get {
                return ResourceManager.GetString("ChangePassForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите язык.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комметарии.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение покупки.
        /// </summary>
        public static string ConfirmPurch {
            get {
                return ResourceManager.GetString("ConfirmPurch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактные Данные.
        /// </summary>
        public static string ContData {
            get {
                return ResourceManager.GetString("ContData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержимое.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать комметарий.
        /// </summary>
        public static string CreateComment {
            get {
                return ResourceManager.GetString("CreateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создано.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string CreateNav {
            get {
                return ResourceManager.GetString("CreateNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новый аккаунт.
        /// </summary>
        public static string CreateNewAcc {
            get {
                return ResourceManager.GetString("CreateNewAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to если у вас нет аккаунта..
        /// </summary>
        public static string DontHaveAcc {
            get {
                return ResourceManager.GetString("DontHaveAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почта.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя либо пароль введены неверно..
        /// </summary>
        public static string ErrorLoginOrPass {
            get {
                return ResourceManager.GetString("ErrorLoginOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при обработке запроса..
        /// </summary>
        public static string ErrorMess {
            get {
                return ResourceManager.GetString("ErrorMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий пароль неверный либо неправильный новый пароль.
        /// </summary>
        public static string ErrorPass1 {
            get {
                return ResourceManager.GetString("ErrorPass1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно создать аккаунт. Пользователь с именем \.
        /// </summary>
        public static string ErrorUsr1 {
            get {
                return ResourceManager.GetString("ErrorUsr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to уже существует..
        /// </summary>
        public static string ErrorUsr2 {
            get {
                return ResourceManager.GetString("ErrorUsr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким именем уже существует. Пожалуйста, введите другое имя.
        /// </summary>
        public static string ErrorUsrName {
            get {
                return ResourceManager.GetString("ErrorUsrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внешний логин был удалён..
        /// </summary>
        public static string ExtLoginRemover {
            get {
                return ResourceManager.GetString("ExtLoginRemover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти к профилю.
        /// </summary>
        public static string GoProfile {
            get {
                return ResourceManager.GetString("GoProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет, .
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последние.
        /// </summary>
        public static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы вошли как .
        /// </summary>
        public static string LggAs {
            get {
                return ResourceManager.GetString("LggAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма авторизации.
        /// </summary>
        public static string LogInForm {
            get {
                return ResourceManager.GetString("LogInForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете купить встречу с понравившимся вам человеком, и он сходит с вами в кино, прогуляется по парку, поужинает с вами..
        /// </summary>
        public static string Main1 {
            get {
                return ResourceManager.GetString("Main1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здесь каждый продаёт своё время и указывает, как оно может быть использовано..
        /// </summary>
        public static string Main2 {
            get {
                return ResourceManager.GetString("Main2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заработав деньги, можно купить чужое время, или снять их..
        /// </summary>
        public static string Main3 {
            get {
                return ResourceManager.GetString("Main3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string MainNav {
            get {
                return ResourceManager.GetString("MainNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление аккаунтом.
        /// </summary>
        public static string ManAcc {
            get {
                return ResourceManager.GetString("ManAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление аккаунтом.
        /// </summary>
        public static string ManYourAcc {
            get {
                return ResourceManager.GetString("ManYourAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница предложения.
        /// </summary>
        public static string OfferPage {
            get {
                return ResourceManager.GetString("OfferPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to предложений.
        /// </summary>
        public static string offers {
            get {
                return ResourceManager.GetString("offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль был изменён..
        /// </summary>
        public static string PassChanged {
            get {
                return ResourceManager.GetString("PassChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль был установлен..
        /// </summary>
        public static string PassSet {
            get {
                return ResourceManager.GetString("PassSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опубликовал.
        /// </summary>
        public static string PostedBy {
            get {
                return ResourceManager.GetString("PostedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о профиле.
        /// </summary>
        public static string ProfileInfo {
            get {
                return ResourceManager.GetString("ProfileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предложения Профиля.
        /// </summary>
        public static string ProfileOffers {
            get {
                return ResourceManager.GetString("ProfileOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказы Профиля.
        /// </summary>
        public static string ProfileOrders {
            get {
                return ResourceManager.GetString("ProfileOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оценить.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма регистрации.
        /// </summary>
        public static string RegForm {
            get {
                return ResourceManager.GetString("RegForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продавец.
        /// </summary>
        public static string Seller {
            get {
                return ResourceManager.GetString("Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить пароль.
        /// </summary>
        public static string SetPass {
            get {
                return ResourceManager.GetString("SetPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас нет местного пароля на этой сайте. Добавив местный.
        /// </summary>
        public static string SetPassPart1 {
            get {
                return ResourceManager.GetString("SetPassPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пароль, вы сможете заходить не используя внешнего..
        /// </summary>
        public static string SetPssPart2 {
            get {
                return ResourceManager.GetString("SetPssPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string SingIn {
            get {
                return ResourceManager.GetString("SingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказ был добавлен в список ваших заказов. Вы можете связаться с продавцом используя его контактные данные.
        /// </summary>
        public static string Success1 {
            get {
                return ResourceManager.GetString("Success1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сонтактные данные продавца.
        /// </summary>
        public static string Success2 {
            get {
                return ResourceManager.GetString("Success2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете просмотреть ваши заказы в профиле.
        /// </summary>
        public static string Success3 {
            get {
                return ResourceManager.GetString("Success3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница успеха.
        /// </summary>
        public static string SuccessPage {
            get {
                return ResourceManager.GetString("SuccessPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тэг.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топ.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Используйте местный аккаунт для входа..
        /// </summary>
        public static string UseLocalAcc {
            get {
                return ResourceManager.GetString("UseLocalAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пользователей.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш коммантарий.
        /// </summary>
        public static string YourComment {
            get {
                return ResourceManager.GetString("YourComment", resourceCulture);
            }
        }
    }
}
